services:
  frontend:
    image: ctink-frontend:latest
    container_name: ctink-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      
  backend:
    image: ctink-backend:latest
    container_name: ctink-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://ctink-mysql:3306/ctink?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_RABBITMQ_HOST=ctink-rabbitmq
      - SPRING_RABBITMQ_PORT=5672

  mysql:
    image: mysql:8.0
    container_name: ctink-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ctink
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 5s
      timeout: 5s     
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ctink-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  mysql_data:
  rabbitmq_data:
