package hyphen.ctink.domain.cti.enums;

public enum CtiPlatform {
    GITHUB_SECURITYONION,
    GITHUB_VELOCIRAPTOR,
    GITHUB_CISCOTALOS,
    GITHUB_STAMPARM,
    GITHUB_ESET,
    GITHUB_AQUASECURITY,
    REDDIT_THREATINTEL,
    REDDIT_BLUETEAMSEC,
    REDDIT_NETSEC,
    REDDIT_CYBERSECURITY,
    MEDIUM_ANYRUN,
    OTX_ALIENVAULT
}
