spring.application.name=ctink

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.property-naming-strategy=SNAKE_CASE

# db
spring.datasource.url = jdbc:mysql://localhost:3306/ctink
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# mq
spring.rabbitmq.host=45.32.51.58
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=StrongPassword123!

# apply
snort.rule.path=/Users/seunghye/Desktop/snort.rules
yara.rule.path=/Users/seunghye/Desktop/yara.yar